<a href="https://colab.research.google.com/github/Shivani-Shreyas/Numpys/blob/master/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

In [3]:
pwd

'/content'

In [0]:
import numpy as np

In [0]:
#The baics....1d array

In [0]:
a = np.array([1,2,3],dtype = 'int 8')

In [7]:
print(a)

[1 2 3]


In [0]:
b = np.array([[1,2,3],[4,5,6]])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b.ndim

2

In [11]:
a.ndim

1

In [12]:
b.shape

(2, 3)

In [13]:
print(a.dtype)

int64


In [0]:
a = np.array([1,2,3])

In [16]:
a.size*a.itemsize

24

In [17]:
a.nbytes

24

In [0]:
#Accessing the data elements

In [0]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])

In [19]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [20]:
a.shape

(2, 8)

In [0]:
random_var = a

In [22]:
type(random_var)

numpy.ndarray

In [23]:
a.dtype

dtype('int64')

In [24]:
a[:,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [0]:
#exercise1

In [0]:
output = np.ones

In [0]:
#advanced concepts
#linearalgebra

a = np.array


In [0]:
c = np.identity(3)

In [27]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.linalg.det(c)

1.0

In [29]:
pwd

'/content'

In [30]:
ls

abc.txt  sample_data/


In [0]:
#read a file using numpy

In [0]:
filedata = np.genfromtxt('abc.txt', delimiter = ',', dtype = 'int8')

In [35]:
filedata

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [36]:
print(filedata)

[ 1  2  3  4  5  6  7  8  9 10]


In [39]:
filedata > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [38]:
np.any(filedata > 5)

True

In [0]:
#NPARRAYCOMPLETION